### PR TITLE
Upgrade to django 2.x

### PR DESCRIPTION
**Pull request by rjauquet**
Howdy Craig 👋 

I forked to get this working with django 2. I'm still working on testing but thought I'd open a PR to see if you had any input.

### CODE REVIEW

**Comment by craiglabenz** [comment]
This looks :+1:

Is the extremely robust test suite passing? :laughing:

**Comment by rjauquet** [comment]
Okay tests are passing now. I didn't exactly know how to update the migrations though. Django 2 requires on_delete to be set now. Do I need to generate a new migration to do that, or is editing the existing migrations fine? That feels a bit bad to do.

**Comment by charettes** [comment]
@rjauquet editing historical migrations for this case is the way to go, even if you were to generate new ones the initialization of `ForeignKey`s would crash anyway. The other option would be to [squash migrations as documented in the release notes](https://docs.djangoproject.com/en/2.1/releases/2.0/#features-removed-in-2-0).

**Comment by craiglabenz** [comment]
Thanks again, @rjauquet and @charettes. Just bumped this on PyPI to `0.7.0` for Django 2.x compatibility. Hope all is well! :smile:

**Comment by charettes** [comment]
Thanks @craiglabenz 🎉 !

**Pull request merged**
